version: '3.4'

services:
  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: store.api/Dockerfile
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "storeuser"
      POSTGRES_PASSWORD: "storeuser"
      POSTGRES_DB: "storedb"
    ports:
      - 5432:5432
       
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

